VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos/6"
  config.vm.hostname = "puppet"
  config.vm.synced_folder "./code", "/vagrant", owner: "vagrant", group: "vagrant", type: "nfs"
  config.vm.network :private_network, ip: "192.168.58.111"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.provision "shell", path: "script.sh"

end

